e2e:
  url: "http://localhost:8080"
  databaseAssert: false # disabled as we expect api+h2 to be running in a container TODO see what we can do
  oauth:
    url: "http://localhost:9090/auth"
    clientId: "community-api-client"
    clientSecret: "community-api-client"
  offenderCrn: X320741
  provider: C21
  team: 200B21
  staff: C21A005
  contacts:
    nsiOnly:
      type: RJC02
      officeLocation: C21ACRC
    nsi:
      type: RJC02
      officeLocation: C21ACRC
      eventId: 2500295343
    notUpdatable:
      type: NOMISE
    updatable:
      type: EAP0
      outcome: CO22
      officeLocation: C21ACRC
      eventId: 2500295343
      requirementId: 2500083652
    event:
      type: COTH
      eventId: 2500295343
    requirement:
      type: COTH
      eventId: 2500295343
      requirementId: 2500083652
    enforcement:
      type: CHVS
      eventId: 2500295343
      outcome: AFTA
      enforcement: ROM
    appointment:
      type: CRSAPT
      eventId: 2500295343
      requirementId: 2500083652
      officeLocation: C21ACRC
  nsis:
    active:
      type: KSS021
      subType: KSS026
      status: SLI01
      eventId: 2500295343
      requirementId: 2500083652
      length: 1
    terminated:
      type: KSS021
      subType: KSS026
      status: SLI01
      outcome: COMP
      eventId: 2500295343
      requirementId: 2500083652
      length: 1
    refer:
      type: KSS021
      subType: KSS026
      status: REFER
      length: 1
  staffs:
    withTeam:
      firstName: Rhiannon
      lastName: Dennis
      provider: C21
      teams:
        - 200B21
  teams:
    default:
      cluster: C21UAT
      ldu: C21UAT
      provider: C21
      type: C21UAT
      description: Test team
      unpaidWorkTeam: false
